# @package _global_
dataset_name: cingulate_babies_left_dHCP_374_subjects
data_dir: "/neurospin/dico/data/deep_folding/current/datasets/dHCP_374_subjects/crops/2mm/CINGULATE.babies/mask/Lskeleton.pkl"
subject_dir: "/neurospin/dico/data/deep_folding/current/datasets/dHCP_374_subjects/crops/2mm/CINGULATE.babies/mask/Lskeleton_subject.csv"
save_dir: "/neurospin/dico/jlaval/Runs/02_STS_babies/Program/Output/BetaVAE/CINGULATE.babies/L/"
in_shape: [1, 22, 62, 49]
