# @package _global_
dataset_name: cingulate_babies_right_dHCP_374_subjects
data_dir: "/neurospin/dico/data/deep_folding/current/datasets/dHCP_374_subjects/crops/2mm/CINGULATE.babies/mask/Rskeleton.pkl"
subject_dir: "/neurospin/dico/data/deep_folding/current/datasets/dHCP_374_subjects/crops/2mm/CINGULATE.babies/mask/Rskeleton_subject.csv"
save_dir: "/neurospin/dico/jlaval/Runs/02_STS_babies/Program/Output/BetaVAE/CINGULATE.babies/R/"
in_shape: [1, 21, 60, 51]
