# @package _global_
dataset_name: cingulate_UKB_right
data_dir: "/neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.babies/mask/Lskeleton.pkl"
subject_dir: "/neurospin/dico/data/deep_folding/current/datasets/UkBioBank/crops/2mm/S.C.babies/mask/Lskeleton_subject.csv"
save_dir: "/neurospin/dico/jlaval/Runs/02_STS_babies/Program/Output/BetaVAE/S.C.babies/L/"
in_shape: [1, 43, 43, 44]
